name: Bildirim Gonder

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  bildirim:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Çek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bagimliliklari Yukle
        run: npm install firebase-admin

      - name: Bildirimleri Gonder
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: node bildirim.js
